# -*- coding: utf-8 -*-
"""exoo5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrzFvCYyfMd_Yusv9FldwUvbC4Gom2NV

partie importer
"""

import csv
import csv
def importer_csv(nom_fichier):
    table = []
    with open(nom_fichier, 'r', encoding='utf-8') as fichier:
        lecteur = csv.DictReader(fichier)
        for ligne in lecteur:
            table.append(ligne)
    return table

importer_csv("utilisateurs.csv")

def creer_table():
    return importer_csv('utilisateurs.csv')

"""partie selectionner"""

def selectionner_moins_300(table):
    resultat = []
    for utilisateur in table:
        if int(utilisateur['jeu1']) < 300:
            resultat.append(utilisateur)
    return resultat

def selectionner_filles(table):
    resultat = []
    for utilisateur in table:
        if utilisateur['sexe'] == 'F':
            resultat.append(utilisateur)
    return resultat

def selectionner_domaine(table):
    resultat = []
    for utilisateur in table:
        if utilisateur['mail'].endswith('@example.fr'):
            resultat.append(utilisateur)
    return resultat

"""partie projecter"""

def projeter_meilleurs_scores(table, jeu):
    scores = []
    for utilisateur in table:
        score = int(utilisateur[jeu])
        scores.append({jeu: score})
    return scores

def scores_tries(table, jeu):
    scores = []
    for utilisateur in table:
        score = int(utilisateur[jeu])
        scores.append({jeu: score})

    scores_tries = sorted(scores, key=lambda x: x[jeu])
    return scores_tries

def score_moyen(table, jeu):
    total = 0
    nb_joueurs = len(table)

    for utilisateur in table:
        total += int(utilisateur[jeu])

    return total / nb_joueurs

def projeter_mail(table):
    adresses = []
    for utilisateur in table:
        adresses.append({'mail': utilisateur['mail']})
    return adresses

def adresses_bad(table, jeu):
    utilisateurs_tries = sorted(table, key=lambda x: int(x[jeu]))
    worseten = utilisateurs_tries[:10]

    adresses = []
    for utilisateur in worseten:
        adresses.append({'mail': utilisateur['mail']})

    return adresses

def enlevedouble(table, jeu):
    utilisateurs_tries = sorted(table, key=lambda x: int(x[jeu]))
    worseten = utilisateurs_tries[:10]
    uniques = []
    mails_vus = []

    for utilisateur in worseten:
        mail = utilisateur['mail']
        if mail not in mails_vus:
            uniques.append({'mail': mail})
            mails_vus.append(mail)
    return uniques